# Generated by Django 4.2.8 on 2024-12-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_quiz_e_alter_gamestats_user"),
    ]

    operations = [
        migrations.DeleteModel(name="Quiz_e",),
    ]
